### ISSUE TITLE
Wont display background image

### ISSUE THREAD

**Issue by OnlyMeMate** [alexa/skill-sample-nodejs-first-apl-skill#3]
Hi,
I'm on module 3 and no matter what I try I can't get the S3 background image to display running it through util.getS3PreSignedUrl(). The cake image displays fine!

In the handler....

   ```javascript
 assets: {
     cake: util.getS3PreSignedUrl('Media/alexaCake_960x960.png'),
     backgroundURL: util.getS3PreSignedUrl('Media/lights_1920x1080.png')
  }
 ```
**However**, if I reference the image URL directly, it works!

   ```javascript
  assets: {
        cake: util.getS3PreSignedUrl('Media/alexaCake_960x960.png'),
        backgroundURL: "https://raw.githubusercontent.com/alexa/skill-sample-nodejs-first-apl-skill/master/modules/assets/lights_1920x1080.png"
}
 ```
Also, if I swap, the images in launchDocument.json, the background image does appear as the "cake", so the image load is working, but the cake image wont fill the background, so it must be some combination of the load method AND the background container......

any ideas?

**Comment by madixon123** [comment]
Hi,

I can't get it to display either. Did you get any further?

**Comment by madixon123** [comment]
It must be their image. I got it to work with another one.
![image](https://user-images.githubusercontent.com/59389346/88076173-a77dbd80-cb71-11ea-88fd-87e00f8fc68c.png)
Using:
    "assets": {
        "cake":"https://github.com/alexa/skill-sample-nodejs-first-apl-skill/blob/master/modules/assets/alexaCake_960x960.png?raw=true",
        "backgroundURL": "https://d2o906d8ln7ui1.cloudfront.net/images/MollyforBT7.png?raw=true"
    }

**Comment by JoeMoCode** [comment]
Hey Madixon123, Were you able to upload the file to your S3 provision with the same name as in the code? The S3 utility is needed to generate the publicly available short lived URL. Help mentioned this in the PR that was open. Did that resolve your issues?

**Comment by sunilvb** [comment]
I have the same exact issue. For some reason, the background image in my APL document won't show up. Event when I use the  document from the official APL documentation example below, it won't show the background image.

https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-alexa-background-layout.html

What was the fix in the above mentioned issue ?

**Comment by JoeMoCode** [comment]
sunilvb there was an issue with the code not being out of sync with the instructions around the data payload. We changed the name from "payload" to support the new syntax of named parameters. Payload is a special parameter name which changes how the data binding works for the document. Using named parameters is generally more intuitive and necessary in some cases. 

That said, sometimes the authoring tool is slow to update the background image. When you have the issue, is it when you try from a skill in the console? The Authoring tool? Or Both?

**Comment by kokhanchyk** [comment]
I faced with the same issue. 
I put my images to my S3 bucket, add cors configuration, and make public. And they work perfect in any component, 
but in  AlexaBackground nothing work, images just didnt appear not in Authoring tool, not on device. 
but that I notice that on example there are query in image url
`?raw=true",`
after I add this query to my image url it works. 
It realy strange behavior, because on other components I dont need to specify this query.

**Comment by JoeMoCode** [comment]
Hi Kokhanchyk,

Thanks for raising this. There is a known issue right now with the AlexaBackground image not displaying in the authoring tool. Workaround is to use FireFox browser.

It sounds like you are talking about something different since the device should not be affected by that. Is there are particular place which did not have the query param for raw=true in the instructions? This is needed when using the GitHub URL for the image which should only really be used with the authoring tool datasource. 

Did adding the param help you with your S3 bucket? If so, this could be due to a bad version being cached with the param breaking that cache. try adding a random query parameter/value and see if that still works in your skill with your S3 URI to confirm.

**Comment by drwhittle** [comment]
I've been using Chrome but I tried the suggested workaround using FireFox but the background image still does not display.  The text (after changing color to red) shows up and the cake image displays but not the background image.  It doesn't display using the github link or S3 bucket URL.  Any suggestions?

**Comment by jallwork** [comment]
Not sure if this helps or is related, but I have an APL alexa-layouts skill that displays an image.
It works fine if I use the amazon link "imageSource": "https://d2o906d8ln7ui1.cloudfront.net/images/MollyforBT7.png"
But if I use the an http link: "imageSource": "http://mywebsite.com/folder/s3Image.jpg" it doesn't work on my device, or if I test it on Chrome, but it does work if I test it on Firefox.
I'll file a report elsewhere

**Comment by jscmidt** [comment]
Sadly I don't have a solution, but just wanted to mention that I have the same issue.
Since this is my first skill it was really annoying, I always thought I made a mistake and searched for hours. Luckily, I now found that it is an issue...

**Comment by jallwork** [comment]
The image should be https to work properly see:
 https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-image.html 

It says: Use https instead of http for image source URLs. Many Alexa devices don't support the http scheme in skill APL documents for security reasons. (which may be why it works sometimes)

If you don’t have https security, follow this excellent video. Make sure you are logged into Virginia though.
https://www.youtube.com/watch?v=lB4DTqMEumY

**Comment by cryptphil** [comment]
I have the same problem. Regardless of whether it is an HTTP or HTTPS URL.

**Comment by balayogesh007** [comment]
Im using custom skill, where can i able to display background image? [JoeMoCode](https://github.com/JoeMoCode)

**Comment by CodeDog23** [comment]
Hello all, I have attempted to reproduce this issue by following module 3 from the beginning, but was able to successfully render both images in the developer console's Alexa simulator and on an Echo Show 5 device using the Alexa-hosted S3 provision. 

I am not certain, but there may have been an issue with AlexaBackground that has since been resolved. If S3 provisioned images are still not rendering for anybody, please make sure the images have been successfully uploaded into the S3 bucket and that the names match between the bucket file name and `util.getS3PreSignedUrl('Media/[filename]')`.

If the issue still persists, deeper investigation into your particular skill can be done if you create a case here: https://developer.amazon.com/alexa/console/contact-us
